### ISSUE TITLE
Review Ticket Week #1

### ISSUE THREAD

**Issue by KoolKidKai** [KoolKidKai/Siuuuu#17]
Lists and Loops Review Ticket (/5)
Team Pages (/2)

- [x] initial requirements, contact info, derivative tangible plans

- [x] Requirements and jobs assigned on scrum board, at least one in progress task

Individual Pages (/3)

- [ ] 5.3 and 5.4 notes and actions

- [ ] key learnings and code snippets; infoDBlists & loops, fibonacci

**Comment by NathanManangan** [comment]
### Team Pages (2/2)

### [Initial requirements](https://koolkidkai.github.io/Siuuuu/plans)
<img width="674" alt="Screen Shot 2022-03-17 at 1 06 07 PM" src="https://user-images.githubusercontent.com/89236893/158886535-c9c42ee1-1a27-4297-9de9-a0f2cbaf0242.png">

### [Contact info](https://koolkidkai.github.io/Siuuuu/TeamSponsors)
<img width="665" alt="Screen Shot 2022-03-17 at 1 07 11 PM" src="https://user-images.githubusercontent.com/89236893/158886667-6f5c9d6a-c02d-46b3-b9cc-680a26159818.png">

### [Derivative tangible plans](https://koolkidkai.github.io/Siuuuu/plans)
<img width="663" alt="Screen Shot 2022-03-17 at 1 09 03 PM" src="https://user-images.githubusercontent.com/89236893/158887264-48cd28ef-4c80-4acb-9ace-5f6d2a7d62aa.png">


### [Requirements and jobs assigned on scrum board ](https://github.com/KoolKidKai/Siuuuu/projects/1)
### [At least one in progress task](https://github.com/KoolKidKai/Siuuuu/projects/1)

# For both:
<img width="736" alt="Screen Shot 2022-03-17 at 1 09 42 PM" src="https://user-images.githubusercontent.com/89236893/158887336-0cbd2325-6d57-438e-9595-4941bc0d6ace.png">

All content is present and easily accessible v.i.a. their Github Pages.

**Comment by jm1021** [comment]
Really nice answer in ticket above.  But what is a "Hack Club"?  It would be nice if this was REALLY focused on Freshmen.  Nice if its connected to National Org.   Technical Plan on data and wires.

1.95/2
